# Generated by Django 5.0.7 on 2024-08-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_payment_link_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank_transfer", "Bank Transfer")],
                default="bank_transfer",
                max_length=20,
            ),
        ),
    ]
