# Generated by Django 5.0.7 on 2024-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("bank_transfer", "Банковский перевод")],
                default="bank_transfer",
                max_length=20,
            ),
        ),
    ]
