# Generated by Django 5.0.7 on 2024-08-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="summ_payment",
            field=models.PositiveIntegerField(verbose_name="сумма платежа"),
        ),
    ]
