# Generated by Django 5.0.7 on 2024-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Наличные в кассу", "Наличные"),
                    ("Банковский перевод", "Банковский перевод"),
                ],
                default="Банковский перевод",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
