# Generated by Django 5.0.7 on 2024-07-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="slug",
        ),
    ]
