# Generated by Django 5.0.7 on 2024-07-25 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_remove_course_slug_remove_lesson_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="name_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="materials.course",
                verbose_name="название курса",
            ),
        ),
    ]
