# Generated by Django 5.0.7 on 2024-08-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ("user",),
                "verbose_name": "Подписку",
                "verbose_name_plural": "Подиписки",
            },
        ),
    ]
