# Generated by Django 5.0.7 on 2024-08-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_subscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.IntegerField(
                blank=True, default=1000, null=True, verbose_name="Стоимость курса"
            ),
        ),
    ]
