# Generated by Django 5.0.7 on 2024-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_alter_course_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="amount",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Стоимость курса, руб"
            ),
        ),
    ]
