# Generated by Django 5.0.7 on 2024-08-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0012_lesson_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Стоимость курса, руб"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Стоимость урока, руб"
            ),
        ),
    ]
